### PR TITLE
Change "Enabled" Audio and Subtitle Tracks by Language so that AppleTV will play the enabled track by default. 

### PR DESCRIPTION
**Pull request by JeffroDH**
The functions to change the subtitle and audio tracks by language function, but the UI needs some work be right.

### CODE REVIEW

**Comment by JeffroDH** [comment]
Got this running locally, works as expected. One thing I'm seeing that's different: The toolbar buttons on the queue menu seem to be on a second row with the title centered, whereas in the latest release in main, the Queue title and toolbar buttons appear on the same row with the toolbar buttons aligned to the right corner.  I didn't make any changes to the Queue UI, not sure why it's appearing that way in my local build.

**Comment by galad87** [comment]
I think it needs a clearer label to better describe what it does, it wasn't clear to be what was supposed to do.
The action needs to enable at most one track, a mp4 might have multiple tracks with the same language, but with different media characteristics.

The whole "default" concepts depends on the player, in an alternate group there isn't a "default" track, the player is supposed to select the best track depending on the player settings, not on what's enabled in the mp4. But I guess this could be useful for some players.

**Comment by JeffroDH** [comment]
Ok! The fix I implemented "selects" the track in the file (like clicking
the checkbox) if it matches the selected language.  The logic
implementation is essentially the same for both audio tracks and
subtitles.  First, I check to see what the mediaType is to determine which
type of file and then if there is a match to the chosen language, it
enables the track.

I see a fair point where you have a main audio track in English and perhaps
a commentary audio track in English.  As it stands, both would be selected.
I'll try and find the mediaType data that will let me preferentially select
the audio track that is marked as "Main Program Content", and then disable
other audio tracks.  I could do the same with the subtitle tracks, if the
data point exists.

Beyond "Main Program Content" and "Auxiliary Content, I don't see anywhere
else I should filter.

I implemented this feature because when I send a file into the Apple TV
library and play it through an AppleTV device or with the app, the
"selected" audio track is the one that plays by default.  This allows me to
change the language track that plays by default in that scenario.  I
understand that not every player implements playback in the same way...

Would making the changes for the specific track selection satisfy?

**Comment by JeffroDH** [comment]
What behavior do you think would be best in each case? If no track is set to main, go ahead and select one, or make no changes?I need to learn a little more about alternate groups, but I’ll look into it and try to update the logic so you don’t have to spend many cycles on it. On Jun 26, 2024, at 11:12 AM, Damiano Galassi ***@***.***> wrote:﻿
Sorry for the delay, it looks mostly ok, but it should handle the case in which there is no track set to main or when there are multiple alternate groups. I can do it, I am reworking something but in the next weeks I should be able to do it.

**Comment by galad87** [comment]
Committed in 2d98e11 with a few changes.
Now it first try to enable the track with the desired language and tag, if not it tries only with the language, if not it does nothing.

**Comment by galad87** [comment]
Hopefully I didn't break anything

**Comment by JeffroDH** [comment]
> Hopefully I didn't break anything

Cheers!

**Pull request closed without merging**
